# Generated by Django 6.0.2 on 2026-02-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('skill_level', models.CharField(blank=True, max_length=50, null=True)),
                ('learning_goal', models.CharField(blank=True, max_length=100, null=True)),
                ('prog_language', models.CharField(blank=True, max_length=50, null=True)),
                ('study_time', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
